---
title: "Deepgreen 抽样功能的设计和实现"
author: "ftian"
date: "December 7, 2018"
output:
  html_document:
    number_sections: yes
  rticles::ctex:
    number_sections: yes
documentclass: ctexart
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# 简介和语法
抽样是指从一个目标总体中抽取一定数量的样本，通过对样本的观察得到对总体的具有一定可靠性的估计。对于大量数据中抽取固定 K 个样本， 最常见的实现是水塘抽样算法。 就数据库而言，总体可以是某个表，也可以是一个查询结果。 在数据库外，特别是并行数据库外，用户实现一个正确的水塘抽样有如下等困难。

* 数据库会对整个查询进行优化， 使用随机函数做的判断有可能被数据库优化后提早或拖后执行。这样抽样不再是随机的。
* 使用游标并抽取前 K 条数据得到的抽样不是随机的。
* 使用游标实现水塘抽样算法。 这个算法实现比较复杂，对用户要求比较高。 同时，需要把所有的数据集中到一个节点计算。  

对大型的并行数据库，这样的数据集中效率是非常低的。
因为以上原因，Deepgreen 数据库内建了分布式的水塘抽样算法。

## limit sample 语法
增加了新语法， 对表或子查询进行随机抽样。
```
select * from T limit sample 100 rows;
select * from T limit sample 10 percent;
```
为了保证随机性， limit sample 是数据库优化器的一个隔离屏障，优化器不会把抽样后执行的判断推到抽样前，也不会把抽样前应该执行的判断留到抽样后执行。

# 分布式的水塘抽样算法
水塘抽样算法可以简单如下描述。 假设我们需要从集合 S 中选取 K 个样本，
```
/* 第一步： 将S中的头K个元素放入水塘中 */
for i = 1 to K
    R[i] = S[i]

/* 第二步： 之后的每个元素，渐渐降低替换入水塘的概率 */
for i = K+1 to |S|
    j := random(1, i)      /* random 包含 1， i */
    if j <= K
        R[j] = S[i]
```
以上水塘抽样算法S中每个元素被抽中的概率是一样的。  水塘抽样算法可以实现有权重的抽样。 在第一步里，我们同时计算水塘的总权重。  第二步里，对后来的每个元素，按照权重决定是否替换入水塘。

对并行数据库里可以使用分布式的水塘抽样算法，
```
/* 第一步： 在每个节点进行水塘抽样。 */
for each node
    run weighted reservoir sampling of K samples
    
/* 第二步： 汇总, */
collect samples from step 1.
    
/* 第三步： 对汇总后的数据进行抽样 */
run weighted reservior sampling of K samples 
using random number generated from Step 1.
```
我们简要说明一下算法里的几点。  首先在每个节点进行抽样时，抽取K个元素。  有些节点可能只有少于K个元素，此时这个算法仍然正确。  在第二步里，我们把所有节点抽样结果汇总，汇总的元素总数不超过 K * #Node。  一般来说汇总的元素远小于数据总量。  在各个节点，元素数量是不一样的。  所以， 第三步里，对汇总后的数据再抽样的时候，我们使用在第一步里产生的随机数 （或需要按各个节点元素数量跟新权重）。   此点对最后抽样随机性至关重要。